Repository kms7530/Salsa, pull requests merged in 2024-10, with the labels that each got.

#25 [Feature] 모델 선택 로드
  service.py
Labels: Enhancement, New Feature

#33 [Example] Pipeline 예제 완성
  api.py
Labels: Documentation

#34 [Docs] License 명시 추가
  LICENSE
Labels: Documentation

#35 [Chore] Black Formatter 수정 반영
  config/config_template.py
  memory_check/memory_profile.py
  memory_check/testcode.py
Labels: Chore

#36 [Chore] Black Formatter 수정 반영
  config/config_template.py
  memory_check/memory_profile.py
  memory_check/testcode.py
  parser/code_generator.py
Labels: Chore
